### ISSUE TITLE
CSS doesn't work

### ISSUE THREAD

**Issue by wodecs** [dataCobra/hugo-vitae#27]
sorry

**Comment by dataCobra** [comment]
Hello @wodecs, the Problem is that you forgot to set the right Link in your configuration of the Website.

In your `config.toml` there is the first row with the following: `baseURL = "http://example.org/"`.

You need to change this to `baseURL = "https://wodecs.github.io/". 

Try this and check if this is a fix for your problem. :slightly_smiling_face: 

Greetings, Ben

**Comment by dataCobra** [comment]
Hey @wodecs, is your problem solved?

I would like to close this issue. :slightly_smiling_face: 

Greetings, Ben

**Comment by wodecs** [comment]
Alright.

________________________________
