### ISSUE TITLE
Changed terms.html broke my site

### ISSUE THREAD

**Issue by karelbemelmans** [dataCobra/hugo-vitae#40]
No change on my site, just doing an update to the latest codebase gives me this error:

ERROR 2020/12/15 21:09:06 render of "taxonomy" failed: "website/themes/hugo-vitae/layouts/_default/terms.html:9:14": execute of template failed: template: _default/terms.html:9:14: executing "main" at <div (sub $maxFontSize $minFontSize) (sub $max $min)>: error calling div: can't divide the value by 0

**Comment by dataCobra** [comment]
Hey @karelbemelmans,

how does your website look at the moment? Can I've a look?

**Comment by karelbemelmans** [comment]
I update to another theme by now, but here is the point in my repo that I was still configured for vitae:

https://github.com/karelbemelmans/personal-website/tree/330696360def370b8ac92ba78be8d6759ff09808

**Comment by dataCobra** [comment]
Hey @karelbemelmans, I think I've fixed your problem.

Please check the version with the new commit.

**Comment by dataCobra** [comment]
I've broke some more give me a sec to fix. Sorry for the problem.

**Comment by dataCobra** [comment]
I've tested the fix now and it finally works. Please test the latest commit version.

**Comment by dataCobra** [comment]
Hey @karelbemelmans,

thank you for reporting this issue. :+1:

While adding this feature I forgot to check what happens when there is one or zero entries in taxonomies.
I took some time now to examine the problem and found a solution for the problem that is now commited.

I would be nice if you could check if this solution works also for your website.

Greetings, Ben

**Comment by karelbemelmans** [comment]
I'll see if I can test it this weekend, thanks for the quick fix!
